# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/patrickniepel/PNCommonsSpecs.git'

target 'NoRest' do
  use_frameworks!
  pod 'ReSwift'
  pod 'SwiftLint'
  pod 'Willow'
  pod 'SCLAlertView'
  pod 'PNCommons'
end
